language: node_js
node_js:
  - 10
install:
  - npm i
script:
  - unset CI
  - npm run build
cache: npm
deploy:
  provider: pages
  local_dir: dist/ngx-popup-app
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
